### ISSUE TITLE
Including Docker in installation instructions?

### ISSUE THREAD

**Issue by daweim0** [CarmeLabs/carme#15]
Do we want to include instructions on how to install Docker? What about installing with anaconda for that mater?

**Comment by jkuruzovich** [comment]
I'll add a note about installing Anaconda. Probably for docker a link to the install directions for Docker would probably do.

**Comment by jkuruzovich** [comment]
Added [here](https://github.com/CarmeLabs/carme/commit/777ad0196146f43cbab9701aa1e93557c830d7fc).
