### ISSUE TITLE
PIP CLI and Caching

### ISSUE THREAD

**Issue by rushsteve1** [CarmeLabs/carme#18]
Add a CLI command for managing PIP packages and writing them to a `requirements.txt` as well as a folder on the host that contains the packages themselves so that containers don't have to re-download all the packages every time they are started.

**Comment by jkuruzovich** [comment]
My concern with this one is that Anaconda is the default data science environment and package manager. 

Check out how effectively it handles multiple dependencies across PIP and 
https://github.com/CarmeLabs/carme/blob/master/src/data/docker/carme-singleuser/config/environment.mac.yml 

I think in any project i'm working on, rarely is there an issue where "I need a thin container for that." Conde might add some bulk, but it is worth it and all the docker stacks containers are build off of Conde.  Could you implement the same thing with conde? I guess is see this as adding a bunch of complexity to keep from redownloading packages. I don't know, might this be something to tackle later? Maybe I don't understand if maybe it is really easy.

**Comment by dmccrevan** [comment]
Is conda typically used when people want to install python packages for Jupyter?

**Comment by jkuruzovich** [comment]
Hmm...no. https://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda.  Conde is a Python+ other stuff package manager, though its main use in this case is installing python and r packages. It allows creating and sharing of environments too.  Jupyter doesn't have any package manager, through there are jupyter extensions which are typically installed as Python packages.

**Comment by jkuruzovich** [comment]
Suggest we close this, as I don't think it is the right approach (when combined with conda).
