### ISSUE TITLE
Git Workflow and Carme new

### ISSUE THREAD

**Issue by jkuruzovich** [CarmeLabs/carme#19]
If I do `careme new sample_package` this initializes a git repository.  

I then try to 

```
git remote add origin https://github.com/CarmeLabs/package_sample.git
git push -u origin master

```
I expect this will add the remote....but instead I get. 

```
error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/CarmeLabs/package_sample.git
```

If instead I clone the repository and then cd into the repository and run `carme new .` I get the error:
```
kc [('Base', <class 'src.cli.commands.base.Base'>), ('New', <class 'src.cli.commands.new.New'>)]
carme: [ERROR] Project folder . already exists
```

I can't run carme new from the parent directory because it gives the error that the directory already exists. 

Suggestions: 
(1) If you create the git repository (I support) provide easy way of adding remote.  I know git and have never seen that error.
(2) Allow running new from local repository and don't do git init if the repository already exists.

**Comment by dmccrevan** [comment]
@jkuruzovich I didn't receive this error when i just did this. I will work on the `carme new .`

**Comment by dmccrevan** [comment]
@jkuruzovich So don't run the git commands if running `carme new .` ? I'm confused on the use case of `carme new .`

**Comment by dmccrevan** [comment]
@jkuruzovich So carme new . would do everything except the git init? Also, I am right now creating a git wrapper for carme. I think the following commands will be for the initial version:
- `carme remote add` will be the same as  `git remote add`
- `carme save <message>` will `git init & git commit -m <message>`
- `carme push` will `git push -u origin master`

Does this sound good?

**Comment by jkuruzovich** [comment]
What if `Carme save`:

(1)  if running for the first time prompted for the name of the remote repository.  Then run:
```
git init 
git add -A
git commit -m "first commit"
git remote add origin <repository>
git push -u origin master 
```
That way you only need the save command?

**Comment by dmccrevan** [comment]
Sure, but I can combine the `save` and `push` but should we keep `remote add` just incase they want to add it later on?

**Comment by jkuruzovich** [comment]
Saving in a local git repository is just something I don't necessarily see the use case for. Yes they would be able to recover commits but only by going deep into git.  

I don't think save should work just locally, as it really doesn't involve a real backup of the code. Should we support changing of remotes with remote add?  I guess I feel like it is standard git and if they want to do anything past saving they might as well learn git.  I don't think we should do much but save, but i'm sure wouldn't be hard to enable changing of the remote.  

Still it isn't a big deal and if you would like to build it, maybe i'm wrong. Once we get to version 1 I can have some students play with it and we can get their thoughts and feedback.  I hate expressing too strong of opinions here when in some ways I'm just imagining how my students and other data scientists will use this. I totally could be wrong about things.

**Comment by dmccrevan** [comment]
@jkuruzovich Good idea on the feedback, for now I will create the two commands `save` and `remote-add`. If they run `save` I will say "not linked to a remote repository, run `carme remote-add` to do so"

**Comment by jkuruzovich** [comment]
@dmccrevan Regarding updating of the new command, made slight adjustment to remove dag and add app directory to default start. https://github.com/CarmeLabs/package_sample
