### ISSUE TITLE
Need a sample package to base package manager on. 

### ISSUE THREAD

**Issue by jkuruzovich** [CarmeLabs/carme#20]
I was interested in building out some of the potential packages and realized we don't necessarily need a functioning manager but rather just an agreement of how the structure would work.  

My thought is that if it is rather easy to adopt a project to a package there will be more sharing, so we should keep the general directory structure. I added a dash directory.  I don't know if we should go opinionated here and just select dash.  

Maybe keep comments here rather than in the sample package repository.  
https://github.com/CarmeLabs/package_sample  

I know we talked about calling apps but have as packages for now.

**Comment by rushsteve1** [comment]
I agree with the structure. As I mentioned on Slack we should make packages and projects effectively one thing. A package just folder merges with the project. Of course the purpose of the CLI tool would be to manage versions and resolve file conflicts.
