### ISSUE TITLE
Suppress git logging

### ISSUE THREAD

**Issue by dmccrevan** [CarmeLabs/carme#21]
This suggestion is for the `carme new` , `carme save`, `carme connect` commands. As of right now the git commands will log, maybe we should suppress these and just use our own logging.

**Comment by rushsteve1** [comment]
If you want to completely suppress output you could do this:
```python
from subprocess import Popen, DEVNULL
Popen([...], stdout=DEVNULL, stderr=DEVNULL)
```
Though you should probably leave `stderr` and just suppress `stdout`.
```python
Popen([...], stdout=DEVNULL)
```
Makes errors more verbose, but successes quieter.
