### ISSUE TITLE
Git push restrictions

### ISSUE THREAD

**Issue by dmccrevan** [CarmeLabs/carme#22]
The `carme save` automatically will push the contents to the remote repo...if the user is using `http` instead of `ssh` and they don't have their credentials stored, this will break. Any suggestions on fixing? We could require `ssh` or maybe when they install carme we have them enter their github credentials and we cache them for them?

**Comment by jkuruzovich** [comment]
Won’t it ask them to log in? Is this to the point where I could try the workflow?

**Comment by dmccrevan** [comment]
@jkuruzovich Yes you could try the workflow...so when you run with http, it will run the work flow but it doesn't allow the user to enter in the credentials.
