### ISSUE TITLE
Move Git code into the modules folder

### ISSUE THREAD

**Issue by rushsteve1** [CarmeLabs/carme#24]
Opening this because the Git related code is not mine so I wanted @dmccrevan to provide some input.

The code in `cli/git.py` should probably be in the `modules` folder, and a different `git.py` in `cli` just acting as a wrapper. This moves the important Git logic away from the CLI and makes it more portable. Anything else towards this end is related to this.

**Comment by dmccrevan** [comment]
@rushsteve1 Good idea, I can move this
