### ISSUE TITLE
Skeleton for package.

### ISSUE THREAD

**Issue by jkuruzovich** [CarmeLabs/carme#3]
This was a nice baseline. 
https://github.com/rdegges/skele-cli

and blog post.
https://stormpath.com/blog/building-simple-cli-interfaces-in-python

This is the current repository. 
https://github.com/Kuberlytics/kubelaunch-cli  

If anyone has opinions, please let me know.

**Comment by dmccrevan** [comment]
I just created the directory, but I am not going to mark as done until we have answered this: Do we want any additonal markdown files such as CONTRIBUTING.md or changelog?

**Comment by rushsteve1** [comment]
@dmccrevan Maybe a changelog, but it's probably too early to worry about a contribution guide.

Though those may be famous last words...
