### ISSUE TITLE
Docker repository and Binder

### ISSUE THREAD

**Issue by jkuruzovich** [CarmeLabs/carme#47]
http://retreat16.readthedocs.io/en/latest/making%20binder/

Binder is an easy way to share lessons via docker containers.  It uses repo to docker to build a project.  I'm just realizing that the carme directory structure currently is not compatible. The Dockerfile has to be at the base of the repository I think. https://mybinder.org  

Should we make this the case by default or no?

**Comment by dmccrevan** [comment]
I don't think this has to do with the carme core...this has to do with the Jupyter plugin, carme is not shipping with built-in juypter support

**Comment by dmccrevan** [comment]
@jkuruzovich Any update on this?

**Comment by jkuruzovich** [comment]
OK. I think it could be a design consideration for the Jupyter package.
