### ISSUE TITLE
Change to f'strings

### ISSUE THREAD

**Issue by jkuruzovich** [CarmeLabs/carme#5]
https://cito.github.io/blog/f-strings/

This fits what I've been doing but is more elequent.  

`commands['delete']="az aks delete --name "+lc['a_cluster_name']+" --resource-group "+ etc. `
would become:

`commands['delete']="az aks delete --name {lc['a_cluster_name']} --resource-group "+ etc. `

is Python 3.6 too recent to require for the package though?

**Comment by rushsteve1** [comment]
Is this as an alternative to `docopts`?
In either case I would say 3.6 is too recent. A lot of distros, Debian stable for instance, are shipping 3.5.x still.

**Comment by daweim0** [comment]
I know its been a few days, but I agree that python 3.5 is probably better right now. 3.5 is the best supported version of python 3 (at least in my experience). I agree that they look cool, but the new format strings don't seem worth the headache of requiring python 3.6
