### ISSUE TITLE
Refactor and Cleanup

### ISSUE THREAD

**Issue by rushsteve1** [CarmeLabs/carme#56]
The code as it stands is a bit of a mess so we need to clean it up a good bit.
To that end we are going to be doing a few things
- [ ] Run pylint and fix all errors
- [ ] Fix Documentation issues (pylint)
- [ ] Remove as many bash commands as possible
- [ ] Remove yaml-merge if possible

**Comment by rushsteve1** [comment]
Related to part 4 of the above list we need to research if we can remove the yaml-merge functionality entirely.
This would also be a good opportunity to look into updating all dependencies.

**Comment by jkuruzovich** [comment]
Can you explain more?  I think that the docker compose file is the only one that is currently merged.  I'm not sure of anyway around merging that.

**Comment by rushsteve1** [comment]
Docker Stack itself was gaining support for supplying multiple compose files to the CLI tool. In that case a yaml-merge tool is unnecessary. Additionally if we could do that as part of the API and not a wrapped bash command that would be nice, but not mandatory.

**Comment by rushsteve1** [comment]
With the merge of the refactor branch I am closing this
