### ISSUE TITLE
Some dependencies were removed from pip and break setup

### ISSUE THREAD

**Issue by SummerRayMorrow** [CarmeLabs/carme#64]
It looks like they are all maintained by the same person who removed them. They are dependencies of gitconfig package. Try doing a --no-cache-dir install since current developers might have it cached.

https://github.com/looking-for-a-job

https://pypi.org/project/assert_exists/
https://pypi.org/project/objectname/
https://pypi.org/project/caller_module/
https://pypi.org/project/tolist/

**Comment by jkuruzovich** [comment]
I think we have fixed the dependency issues so that install is working.  However, I'd like to directly review all the dependencies to see which are actually used.  @rushsteve1 If you could try again and let us know if it is working for you.

**Comment by rushsteve1** [comment]
This should have been fixed when I redid the dependencies.
