### ISSUE TITLE
Carme new <projectname> creates project folder with docker-compose.yml inside

### ISSUE THREAD

**Issue by jkuruzovich** [CarmeLabs/carme#7]
When typing `carme new <projectname>` the user will be created a new folder (named according to project name) with the following directories/files.  

```
./dags/
./notebooks/
launchfile.yaml
docker-compose.yaml
```

A sample `docker-compose.yml` file is located in `/src/data/docker/docker-compose.yml` and running `docker-compose up` will launch the 3 containers.  The volume system is such that a dag created on the jupyter notebook could be moved across to the airflow container.

**Comment by dmccrevan** [comment]
Is there a sample `launchfile.yaml` to copy from?

**Comment by jkuruzovich** [comment]
Right now I had been putting `launchfiles` files for each app in `https://github.com/CarmeLabs/carme/tree/master/src/data/launch_files`. I guess you should probably create one that is equivalent to a base or starter file? In the jupyter example I ask a question...maybe we could ask something like this. 
Enter your project des

**Comment by dmccrevan** [comment]
Just pushed this to feature, @jkuruzovich @daweim0 @rushsteve1 if you guys want to check it out, see if there is any issues with it. If not, we can close this.

**Comment by jkuruzovich** [comment]
@dmccrevan Worked great once I got the configuration right.  Not currently handling the case that the directory already exists though.  I think it should also perhaps have a notebooks folder. Jupyter is central to the project and Jupyter works through notebooks.
  

```
carme: [INFO] Creating new project structure for carmetest
Traceback (most recent call last):
  File "/anaconda3/envs/condetest/bin/carme", line 11, in <module>
    load_entry_point('carme', 'console_scripts', 'carme')()
  File "/Users/jasonkuruzovich/githubdesktop/0_class/carme/src/cli/cli.py", line 45, in main
    cli(options)
  File "/Users/jasonkuruzovich/githubdesktop/0_class/carme/src/cli/cli.py", line 59, in cli
    command.run()
  File "/Users/jasonkuruzovich/githubdesktop/0_class/carme/src/cli/commands/new.py", line 29, in run
    os.mkdir(self.project_dir)
FileExistsError: [Errno 17] File exists: '/Users/jasonkuruzovich/githubdesktop/0_class/carmetest'
```

**Comment by dmccrevan** [comment]
@jkuruzovich Just fixed this, good to close?

**Comment by jkuruzovich** [comment]
Nice. I got the error `Project already exists with give name.`  Should be 
'given' I think or how about `Project folder <name> already exists.` Also, while the `launchfile.yaml` is there the `docker-compose.yaml` is not. Should it be?

**Comment by dmccrevan** [comment]
@jkuruzovich Just changed the error message, but the `docker-compose.yaml` is within the `docker/` directory.
