### ISSUE TITLE
Fix Carme installation

### ISSUE THREAD

**Issue by dmccrevan** [CarmeLabs/carme#83]

**Comment by jbeck18** [comment]
On a mac, I get the following error when running ```pip3 install -r requirements.txt```

![Import Error](https://user-images.githubusercontent.com/9908980/49475686-d81ab300-f7e5-11e8-8861-20a54dd9d579.png)

**Comment by rushsteve1** [comment]
@jbeck18 Does it work with the new requirements file?

**Comment by jbeck18** [comment]
@rushsteve1 I just tried it on gcp and it still didn't work, I got this error:

![image](https://user-images.githubusercontent.com/9908980/49820743-b621b300-fd46-11e8-97b6-9c0fe810eba1.png)
