### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by rushsteve1** [CarmeLabs/carme#9]
The packaging system has a lot to consider so this issue is to track it.

Necessary Features
- [ ] Install a package file to a project
- [ ] Pull a package from a repository
- [ ] Some form of package dependency resolution (Overlays?)
- [ ] Figure out the best way to make packaging git-portable.
- [ ] Package updating.

**Comment by rushsteve1** [comment]
#20 Is related to this.

**Comment by rushsteve1** [comment]
Commit d380da9 has the basic functionality of the package management system. It still needs to be tested but the current code hopefully allows you to install and remove packages both from a local zip or directory, or from a URL.

**Comment by jkuruzovich** [comment]
One question is how to potentially include cli functions in the package.  I've put some details in /data/packages/gcp/commands.

Maybe a command.yaml file could have lists that could then be combined? 

```
lc={}
lc['a_resource_group']= "myresoure"
lc['a_location']= "mylocation"
create_project=["az group create --name",lc['a_resource_group'], "--location ", lc['a_location']]
create_projectcmd= ' '.join(create_project)
```

Alternately, maybe some type of templating system. This is a little more clear. The idea would be that packages could be included. 
`create_project:    "az group create --name {resource_group} --location {location}"`

**Comment by jkuruzovich** [comment]
@rushsteve1 The package command should concatenate the carme-command.yaml file.  I've also designed functionality so that the carme-config.yaml should be concatenated. I was doing this in the `append_launch_file function` previously.  This is a pretty critical aspect.  

```

    def append_launch_file(self, app):
        app_config=self.launch_dir+'/apps/'+app+'.yaml'
        if os.path.isfile(app_config):
            print('Adding configuration for '+app+' to config.yaml.')
            config=self.load_yaml(app_config)
            ruamel.yaml.round_trip_dump(config, open(self.launch_file, 'a'))
            self.launch_config=self.load_yaml(self.launch_file)
            if app=='jupyter':
                jupyter_init(self)
        else:
            print('The configuration for the application ', app, 'is not available.' )
        copyfile(self.notebooks_dir+'/apps/'+app+'.ipynb', self.cwd+'/'+app+'.ipynb')
```
